### ISSUE TITLE
Review feedback

### ISSUE THREAD

**Issue by teddyjtorres** [OpenLiberty/draft-guide-security-intro#51]
Thank you for creating this guide. Here are a comments:

1. The guide refers to identity store throughout, while it actually defines a user registry. It is suggested to use User Registry instead since that is the technical term. While identity store is a general security term, it is also a very specific interface of the Java EE Security API Specification that this guide does not use.

2. For "Form authentication allows you to specify the web application login and error pages, assign the security constraint of a servlet and use the SecurityContext API to determine the role of a logged in user.", it implies that assigning constraints and programmatic login are functions of Form authentication. It is suggested to split this sentence to probably read like, "Form authentication allows you to specify the web application login and error pages. You'll also assign the security constraint of a servlet and use the SecurityContext API to determine the role of a logged in user."

**Comment by justineechen** [comment]
1) Authentication confirms the identity of the user by verifying a user name and password. --> Authentication confirms the identity of the user by verifying a user's credentials (like user name and password for eg).
2) also, you say bob and Bob etc - may be ok since actual name vs username
3) ID store vs registry - like Teddy pointed out - better to talk in the call
4) why need security constraints in web.xml when you can use annotations for all ? may be because it is jsf file?
4a) Would be good to show all security in annotations - nothing in web.xml
5) error-page is not really related to security- it is webcontainer - may be can be clarified.

**Comment by justineechen** [comment]
Addressed points 1, 2, 3 in 
https://github.com/OpenLiberty/draft-guide-security-intro/pull/52 and we discussed the reasoning behind points 4,5 over a call.

**Comment by evelinec** [comment]
Verified the fixes, looked good.

**Comment by yeekangc** [comment]
Issues addressed.  Closing.

Should request a re-review based on latest changes.
